version: "3.7"

services:
  mongodb:
    image: "mongo:4.4.3"
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - connector
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
  spark_stand:
    build: .
    restart: always
    networks:
      - connector
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    links:
      - mongodb

networks:
  connector:

